<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AgentCQN extends Model {

    public $table = 'agent_cqn';
    public $fillable = ['rid',
        'team',
        'jan_feed',
        'jan_q',
        'jan_fcr',
        'jan_crr',
        'jan_nps',
        'feb_feed',
        'feb_q',
        'feb_fcr',
        'feb_crr',
        'feb_nps',
        'mar_feed',
        'mar_q',
        'mar_fcr',
        'mar_crr',
        'mar_nps',
        'april_feed',
        'april_q',
        'april_fcr',
        'april_crr',
        'april_nps',
        'may_feed',
        'may_q',
        'may_fcr',
        'may_crr',
        'may_nps',
        'june_feed',
        'june_q',
        'june_fcr',
        'june_crr',
        'june_nps',
        'july_feed',
        'july_q',
        'july_fcr',
        'july_crr',
        'july_nps',
        'aug_feed',
        'aug_q',
        'aug_fcr',
        'aug_crr',
        'aug_nps',
        'sept_feed',
        'sept_q',
        'sept_fcr',
        'sept_crr',
        'sept_nps',
        'oct_feed',
        'oct_q',
        'oct_fcr',
        'oct_crr',
        'oct_nps',
        'nov_feed',
        'nov_q',
        'nov_fcr',
        'nov_crr',
        'nov_nps',
        'dec_feed',
        'dec_q',
        'dec_fcr',
        'dec_crr',
        'dec_nps',
    ];

}
