<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AgentProd extends Model {

    public $table = 'agent_prod';
    public $fillable = ['rid',
        'team',
        'teamname',
        'jan_diff',
        'jan_email',
        'jan_sse',
        'jan_calls',
        'jan_prod',
        'feb_diff',
        'feb_email',
        'feb_sse',
        'feb_calls',
        'feb_prod',
        'mar_diff',
        'mar_email',
        'mar_sse',
        'mar_calls',
        'mar_prod',
        'april_diff',
        'april_email',
        'april_sse',
        'april_calls',
        'april_prod',
        'may_diff',
        'may_email',
        'may_sse',
        'may_calls',
        'may_prod',
        'june_diff',
        'june_email',
        'june_sse',
        'june_calls',
        'june_prod',
        'july_diff',
        'july_email',
        'july_sse',
        'july_calls',
        'july_prod',
        'aug_diff',
        'aug_email',
        'aug_sse',
        'aug_calls',
        'aug_prod',
        'sept_diff',
        'sept_email',
        'sept_sse',
        'sept_calls',
        'sept_prod',
        'oct_diff',
        'oct_email',
        'oct_sse',
        'oct_calls',
        'oct_prod',
        'nov_diff',
        'nov_email',
        'nov_sse',
        'nov_calls',
        'nov_prod',
        'dec_diff',
        'dec_email',
        'dec_sse',
        'dec_calls',
        'dec_prod',
    ];

}
