<div>

    <div>
        <p style="font-family: Cambria; font-size: 18px;">Hi!<br>
        {{ $form->agent->name }} has added an action plan.</p>
    </div>
    
    <div style="font-family: Cambria; font-size: 16px">
            Please click the link below to view the form. <br>
<!--            link of the form-->
            <a href="{{ url('coachingform/'.$form->id)}}">{{ url('coachingform/'.$form->id)}}</a>
    </div>
    <br>
    <br>
    <div>
        <small style='font-family: Cambria;'>
            This message is automatically generated by the 1&1 Coaching Tool.<br>
            If you have received this email in error, please notify the IT Department and delete the email.
        </small>
    </div>
</div>
