<div>
    <div>
        <p style="font-family: Cambria; font-size: 18px;">Greetings {{ $com->coachingForm->createdBy->name}} </p>    
        <div style="font-family: Cambria; font-size: 16px">
                You have due Action Plans to evaluate today for your coaching of {{ $com->coachingForm->agent->name }}.<br>
                Please accomplish this action plan the soonest.  <br> <br>

                Please click the link below to view the form. <br>
    <!--            link of the form-->
    <a href="{{ url('coachingform/'.$com->id)}}">{{ url('coachingform/'.$com->id)}}</a><br><br>
        </div>
        <br>
    </div>
    <div>
        <small style='font-family: Cambria;'>
            This message is automatically generated by the 1&1 Coaching Tool.<br>
            If you have received this email in error, please notify the IT Department and delete the email.
        </small>
    </div>
</div>
