<div>

    <div>
        <p style="font-family: Cambria; font-size: 18px;">Hi, {{$form->createdBy->name }}!<br>
        You have successfully made a new coaching form.</p>
        <br>
    </div>
    
    <div style="font-family: Cambria; font-size: 16px">
            Coaching Form Type: {{ $form->type }} <br>
            Created by: {{ $form->createdBy->name }} <br>
            Agent: {{ $form->agent->name }} <br><br>
            
            Please click the link below to view the form. <br>
<!--            link of the form-->
            <a href="{{ url('coachingform/'.$form->id)}}">{{ url('coachingform/'.$form->id)}}</a>
    </div>
    <br>
    <br>
    <div>
        <small style='font-family: Cambria;'>
            This message is automatically generated by the 1&1 Coaching Tool.<br>
            If you have received this email in error, please notify the IT Department and delete the email.
        </small>
    </div>
</div>



