<div>

    <div>
        <p style="font-family: Cambria; font-size: 18px;">Hi!</p>
        <br>
    </div>
    <div style="font-family: Cambria; font-size: 16px">
        Your coaching of {{ $form->agent->name }} has been updated. <br>
        Please click the link below to view the form and its changes. <br>
<!--            link of the form-->
         <a href="{{ url('coachingform/'.$form->id)}}">{{ url('coachingform/'.$form->id)}}</a>
    </div>
    <br>
    <br>
    <div>
        <small style='font-family: Cambria;'>
            This message is automatically generated by the 1&1 Coaching Tool.<br>
            If you have received this email in error, please notify the IT Department and delete the email.
        </small>
    </div>
</div>
