<div>
    <div>
        <p style="font-family: Cambria; font-size: 18px;">Greetings {{ $form->agent->name }}.</p>
        <div style="font-family: Cambria; font-size: 16px">
        <p style="font-family: Cambria; font-size: 16px;"> @if ($form->status == "Pending")
                                                            You have changed the status of a coaching form to ongoing.
                                                            @elseif ($form->status == "Ongoing")
                                                            You have successfully completed a coaching form. Good Job!
                                                            @endif<br></p>
    </div>
    
    <div style="font-family: Cambria; font-size: 16px">
        Please click the link below to view the completed form. <br>
<!--            link of the form-->
        <a href="{{ url('coachingform/'.$form->id)}}">{{ url('coachingform/'.$form->id)}}</a>
    </div>
    <br>
    <br>
    <div>
        <small style='font-family: Cambria;'>
            This message is automatically generated by the 1&1 Coaching Tool.<br>
            If you have received this email in error, please notify the IT Department and delete the email.
        </small>
    </div>
</div>
