<div>
    <p>Good day, {{$name}}! A  new issuance has been issued under your name.</p>
    <p>You may click <a href="<?php echo asset('/assets/view/').'/'.$issued_id ?>">here</a> to view request or visit the department office to claim issued items listed below. </p>
    <?php $issue = DB::table('assets_issuance_item')->where('issued_id', $issued_id)->get(); ?>
    <div style="padding-left: 30px;">
    <table style="border-collapse:collapse; width:400px; border: 1px solid #F4F4F4;">
        <thead>
            <tr>
                <th style="border: 1px solid #F4F4F4; font-size: 14px; color: #333; padding: 6px 6px 6px 6px; width: 50%; background-color: #F9F9F9;">Item</th>
                <th style="border: 1px solid #F4F4F4; font-size: 14px; color: #333; padding: 6px 6px 6px 6px; width: 50%; background-color: #F9F9F9;">Quantity</th>
            </tr>
        </thead>
        <tbody>
        @foreach($issue AS $i)
            <?php $item = DB::table('assets_items')->where('id', $i->item_id)->first(); ?>
            <tr>
                <td style="border: 1px solid #F4F4F4; font-size: 14px; color: #333; padding: 6px 6px 6px 6px; text-align: center; vertical-align: center;">{{ $item->name }}</td>
                <td style="border: 1px solid #F4F4F4; font-size: 14px; color: #333; padding: 6px 6px 6px 6px; text-align: center; vertical-align: center;">{{ $i->quantity }}</td>
            </tr>
        @endforeach
            
        </tbody>
    </table>
    </div>
</div>
<hr>
This message is automatically generated by the 1&1 Assets Tracking Tool.<br>
If you have received this email in error, please notify the IT Department and delete the email.
