<table id="agent_stats" style="border-collapse: collapse; clear: both; margin-top: 6px !important; margin-bottom: 6px !important; width: 1050px; border: 2px solid #F4F4F4;">
    <thead>
        <tr><th style="border: 2px solid #F4F4F4; font-family: Helvetica,Arial,sans-serif; font-weight: bold; font-size: 14px; color: #333; padding: 6px 6px 6px 6px; width: 15%; background-color: #F9F9F9;">Agent Name</th>
            <th style="border: 2px solid #F4F4F4; font-family: Helvetica,Arial,sans-serif; font-weight: bold; font-size: 14px; color: #333; padding: 6px 6px 6px 6px; width: 15%; background-color: #F9F9F9;">Total Calls <br>of the Week</th>
            <th style="border: 2px solid #F4F4F4; font-family: Helvetica,Arial,sans-serif; font-weight: bold; font-size: 14px; color: #333; padding: 6px 6px 6px 6px; width: 20%; background-color: #F9F9F9;">Reasons for Zero Sales</th>
            <th style="border: 2px solid #F4F4F4; font-family: Helvetica,Arial,sans-serif; font-weight: bold; font-size: 14px; color: #333; padding: 6px 6px 6px 6px; width: 20%; background-color: #F9F9F9;">Supervisor Action Plan</th>
            
        </tr>
    </thead>
    <tbody>
        <tr><td style="border: 2px solid #F4F4F4; background-color: transparent; font-family: Source Sans Pro, Helvetica Neue,Helvetica,Arial,sans-serif;  font-size: 14px; color: #333; padding: 6px 6px 6px 6px; width: 15%; text-align: center; vertical-align: top;">{{ $agent_name->name }}</td>
            <td style="border: 2px solid #F4F4F4; background-color: transparent; font-family: Source Sans Pro, Helvetica Neue,Helvetica,Arial,sans-serif;  font-size: 14px; color: #333; padding: 6px 6px 6px 6px; width: 15%; text-align: center; vertical-align: top;">{{ $total_calls }}</td>
            <td style="border: 2px solid #F4F4F4; background-color: transparent; font-family: Source Sans Pro, Helvetica Neue,Helvetica,Arial,sans-serif;  font-size: 14px; color: #333; padding: 6px 6px 6px 6px; width: 20%; text-align: center; vertical-align: top;"><?php echo $reasons; ?></td>
            <td style="border: 2px solid #F4F4F4; background-color: transparent; font-family: Source Sans Pro, Helvetica Neue,Helvetica,Arial,sans-serif;  font-size: 14px; color: #333; padding: 6px 6px 6px 6px; width: 20%; text-align: center; vertical-align: top;"><?php echo $sup_actionplan; ?></td>
            
        </tr>
    </tbody>
</table>
<br>----------------------------------------------------------------------------------------------------------------------------------
<br>This message is automatically generated by the 1&1 SAS Low Performers Tool.
<br>If you have received this email in error, please notify the IT Department and delete the email.