<?php

echo '<p style="font-family: arial; font-size: 12px;">Hi!<br>';
echo 'Check your validated SAS payout with the link below:<br><br>';
echo 'URL: <a href="' . url('sas/payouts') . '">' . url('sas/payouts') . '</a><br><br>';
echo "-----------------------------------------------------------------------------------------<br>";
echo "<div style='text-align: left; font-size: 12px; font-family: arial;'>This message is automatically generated by the 1&1 MIS-EWS Website.<br>";
echo "If you have received this email in error, please notify the IT Department and delete the email.<br>";
